version: '3.7'
services:
 postgres:
  restart: always
  container_name: dndServer_postgres
  build: 
   context: .
   dockerfile: dockerfiles/docker_postgres.conf
  volumes:
      - ./dbdata:/var/lib/postgresql/data
 django:
  restart: always
  container_name: dndServer_django
  volumes:
   - ./code:/code
   - sock:/sock
  build: 
   context: .
   dockerfile: dockerfiles/docker_django.conf
  depends_on:
   - postgres
  command: uwsgi --ini /etc/uwsgi.ini
  #command: bash -c "python /code/dndServer/manage.py collectstatic --noinput && python /code/dndServer/manage.py migrate && python /code/dndServer/manage.py runserver 0.0.0.0:8000"
  ports:
   - "8000:8000"
 nginx:
  restart: always
  container_name: dndServer_nginx
  volumes:
   - ./code:/code
   - sock:/sock
  build:
   context: .
   dockerfile: dockerfiles/docker_nginx.conf
  depends_on:
   - django
  ports:
    - "8080:8080"
volumes:
 sock: